# VARIABLES
QUANTITY_PATTERN = r'^\(\d+\svnt.\)\s'

# MESSAGES to VBA
VBA_ERROR_ALERT = 'ERROR_CALL_DADDY'
VBA_ALREADY_OPEN_ERROR = 'AMAZON WORKBOOK OPEN'
VBA_NO_NEW_JOB = 'NO NEW JOB'
VBA_KEYERROR_ALERT = 'ERROR_IN_SOURCE_HEADERS'
VBA_OK = 'EXPORTED_SUCCESSFULLY'

# Workbooks
EXPORT_FILE = 'Amazon Inventory Reduction.xlsx'
SKU_MAPPING_WB_NAME = 'Amazon SKU Mapping.xlsx'
SHEET_NAME = 'SKU codes'
HEADERS = ['sku', 'quantity', 'item']